In [2]:
#for kernel command is-> python -m ipykernel install --user --name=cuda --display-name "nameofkernel"

import torch

In [3]:
#PYTORCH FUNCTIONS

In [4]:
#.randint(lower limit, upper limit, size) returns a tensor filled with random integers
randint = torch.randint(-20, 20, (4,))
randint

tensor([-13,   7,  12,  16])

In [5]:
#.tensor are multidimensional arrays
tensor = torch.tensor([[0.1, 4.4], [2.5,3.6], [4.5,9.8]])
tensor

tensor([[0.1000, 4.4000],
        [2.5000, 3.6000],
        [4.5000, 9.8000]])

In [6]:
#.zeros and .ones matrices of 0s and 1s of given (rows,columns)
zeros = torch.zeros(2,4)
print(zeros)
ones = torch.ones(3,5)
ones
#in the form of floating point numbers

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
#.empty(rows,colmns)
input = torch.empty(2,3)
input

tensor([[5.3928e-05, 6.5260e-10, 2.1860e-04],
        [3.3091e-09, 2.1495e-04, 3.3884e-06]])

In [8]:
#.arange (no. of elements, starts from 0)
arange = torch.arange(6)
arange

tensor([0, 1, 2, 3, 4, 5])

In [9]:
#.linspace and .logspace for reaching from given start to end points within given steps
#writing 'start' and 'end' is optional
linspace = torch.linspace(start=4, end=15, steps=4)
print(linspace)

logspace = torch.logspace(start=-10, end=10, steps=5)
print(logspace)

tensor([ 4.0000,  7.6667, 11.3333, 15.0000])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [10]:
#.eye(no.of rows&columns)
#diagonal line of 1. Reduced row eucheleon form?
eye = torch.eye(4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [11]:
#.empty_like(input) returns an uninitialized tensor with the same size as input.
#'input' defined above
empty_like = torch.empty_like(input, dtype=torch.int64)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
#.multinomial(prob., no. of samples, repl)
probabilities = torch.tensor([0.3, 0.7])
#0.3 or 30% => 0(index) and 0.7 or 70% => 1(index)
# each probablity points to the index of the probability in the tensor
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples

tensor([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [13]:
#.cat i.e. concatenate (tensor1, tensor2, dim=0/1)
#If dim=0, the tensors are concatenated column-wise; if dim=1, the tensors are concatenated row-wise.
tensor = torch.zeros(2,2)
out = torch.cat((tensor, torch.ones([2,2])), dim=0)
print(out)
out = torch.cat((tensor, torch.ones([2,2])), dim=1)
out

tensor([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]])


tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])

In [14]:
#.tril is (l)ower triangle, returns diagonal lower traingle
ones = torch.ones(5,5)
tril = torch.tril(ones)
print(tril)

#.triu is (u)pper diagonal triangle, of given input
triu = torch.triu(torch.ones(5,5))
triu

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [15]:
#.masked_fill(mask(BooleanTensor), value) fills elements of self tensor with value where mask is True.
msk = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
print(msk)

#.exp(x) calculates e^x, where e is the base of the natural logarithm (approximately 2.71828).
exponential = torch.exp(msk)
exponential
# -inf exp is 0, 0 exp is 1

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [16]:
#.transpose(0th(1st dimension),1,2) swapping/flipping dimensions of a tensor
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [17]:
#.stack(tensor1, tensor2, ...) ex:for stacking blocks, hence creating batches
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = torch.tensor([7,8,9])
#stacks tensors along a new dimension
stacked_tensor = torch.stack([t1,t2,t3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
#.nn.Linear(in_features(int)(size of each input sample), out_features(int)(size of each output sample),
# bias(bool)(false, the layer will not learn an additive bias.)) 

#done to find best parameters for transformation?

import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-8.1082, -3.8145, -0.5405], grad_fn=<SqueezeBackward4>)


In [19]:
#.softmax(input)
#calculates the exponential of each element in the input vector, then normalizes the resulting values by
#dividing each element by the sum of all exponentials, transforming the input vector into a probability distribution
#where the elements now represent the probabilities of different classes.

import torch.nn.functional as F
tensor1 = torch.tensor([1.0, 2.0, 3.0])
softmax_output = F.softmax(tensor1, dim=0) #dim refers to the dimension in which it outputs
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [28]:
#.Embedding(vocab_size, dimensionality of embedding vector)
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)
input_indices = torch.LongTensor([1,5,3,2])
output = embedding(input_indices)
print(output.shape)

torch.Size([4, 100])


In [87]:
#matrix multiplications - @ and .matmul
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[5,4,8],[3,2,6]])
print(a @ b)
#can also use (torch.matmul(a,b))
print(torch.matmul(a,b))

tensor([[11,  8, 20],
        [27, 20, 48],
        [43, 32, 76]])
tensor([[11,  8, 20],
        [27, 20, 48],
        [43, 32, 76]])


In [88]:
#int and float datatypes can't be multiplied together unless .float() to convert int to float
#float to int not recommended since we need room for points to be precise
#.randint for integers and .rand for floating point numbers
int = torch.randint(0,1, (3,2)).float()
float = torch.rand(2,3)
result = torch.matmul(int, float)
print(int.dtype, float.dtype)
result

torch.float32 torch.float32


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [89]:
# .shape into .view 
# .shape unpacks dimensions
# .view to make the tensor again with given .shape dimensions
a = torch.rand(2, 4, 6)
print(a.shape) #using .shape again to just view the dims.

x, y, z = a.shape
a = a.view(x, y, z)
print(a.shape)

torch.Size([2, 4, 6])
torch.Size([2, 4, 6])


In [90]:
#Activation functions: ReLU, sigmoid, tanh
x = torch.tensor([1], dtype=torch.float32)
y = F.sigmoid(x) #sigmoid outputs values between 0 and 1
z = F.tanh(x) #tanh outputs values between -1 and 1
print(y, z) 

tensor([0.7311]) tensor([0.7616])
